routes/web.php
<?php

use App\Http\Controllers\EpisodeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home-page');
Route::get('/danh-muc/{slug}', [App\Http\Controllers\IndexController::class, 'category'])->name('category');
Route::get('/the-loai/{slug}', [App\Http\Controllers\IndexController::class, 'genre'])->name('genre');
Route::get('/phim/{slug}', [App\Http\Controllers\IndexController::class, 'movie'])->name('movie');
Route::get('/xem-phim/{slug}', [App\Http\Controllers\IndexController::class, 'watch'])->name('watch');
Route::get('/quoc-gia/{slug}', [App\Http\Controllers\IndexController::class, 'country'])->name('country');
Route::get('/so-tap', [App\Http\Controllers\IndexController::class, 'episode'])->name('so-tap');
Route::get('/year/{slug}', [App\Http\Controllers\IndexController::class, 'year'])->name('year');
Route::post('/update-topview-phim', [MovieController::class,'update_topview']);
Route::post('/update-season-phim', [MovieController::class,'update_season']);
Route::get('/tim-kiem', [App\Http\Controllers\IndexController::class,'search'])->name('search');
Route::get('/select-movie', [EpisodeController::class,'select_movie'])->name('select-movie');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/', App\Http\Controllers\IndexController::class);
Route::resource('/category', App\Http\Controllers\CategoryController::class);
Route::resource('/genre', App\Http\Controllers\GenreController::class);
Route::resource('/movie', App\Http\Controllers\MovieController::class);
Route::resource('/watch', App\Http\Controllers\WatchController::class);
Route::resource('/country', App\Http\Controllers\CountryController::class);
Route::resource('/episode', App\Http\Controllers\EpisodeController::class);

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Scripts -->
    {{-- @vite(['resources/sass/app.scss', 'resources/js/app.js']) --}}
    <link rel='stylesheet' id='bootstrap-css' href='{{asset('css/bootstrap.min.css?ver=5.7.2')}}'  />
      <link rel='stylesheet' id='style-css' href='{{asset('css/style.css?ver=5.7.2')}}'  />
      <link rel='stylesheet' id='wp-block-library-css' href='{{asset('css/style.min.css?ver=5.7.2')}}'  />
      <script type='text/javascript' src='{{asset('js/jquery.min.js?ver=5.7.2')}} '></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
             @if( Auth::user()->id)
                <div class="container">
                    @include('layouts.navbar')
                </div>
             @endif
            @yield('content')
        </main>
    </div>

    {{-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> --}}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script type="text/javascript">
    //    $('#timkim-form').click(function() { 
    //         $('#slider').anythingSlider($("#input1").val()); 
           
    //     });
    </script> 
    <script type="text/javascript">
        $('.select-movie').change(function(){
            var id = $(this).val();          
            $.ajax({
                url:"{{url('/select-movie')}}",
                method:'get',
                data:{id:id},
                success:function(data){
                    $('#show_movie').html(data);
                }
            })
        })
    </script> 
   <script type="text/javascript">
        $('.select-season').change(function(){
            var season = $(this).find(':selected').val();
            var id_phim = $(this).attr('id');
            var _token = $('input[name="token"]').val();
          
    
            $.ajax({
                url:"{{url('/update-season-phim')}}",
                method:'post',
                data:{season:season,id_phim:id_phim,_token:_token},
                success:function(){
                    alert('Thay đổi phim theo season'+text+'Thành công');
                }
            })
        })
    </script> 
     <script type="text/javascript">
            $('.select_top_view').change(function(){
                var topview = $(this).find(':selected').val();
                var id_phim = $(this).attr('id');
                var _token = $('input[name="_token"]').val();

                if(topview===0){
                    var text = 'Ngày';
                }else if(topview===1){
                    var text= 'Tuần';
                }
                else{
                    var text = 'Tháng';
                }

                $.ajax({
                    url:"{{url('/update-topview-phim')}}",
                    method:'post',
                    data:{top_view:topview,id_phim:id_phim,_token:_token},
                    success:function(){
                        alert('Thay đổi phim theo topview'+text+'Thành công');
                    }
                })
            })
     </script>


</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{route('home')}}">Dardboad</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{route('category.create')}}">Danh mục phim</a>
        </li>
      
        <li class="nav-item active">
          <a class="nav-link" href="{{route('genre.create')}}">Thể loại <span class="sr-only">(current)</span></a>
        </li>
       
        <li class="nav-item">
            <a class="nav-link" href="{{route('country.create')}}">Quốc gia</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="{{route('movie.create')}}">Phim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('episode.create')}}">Tập</a>
          </li>
      </ul>
    
    </div>
  </nav>