routes/web.php
<?php

use App\Http\Controllers\EpisodeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home-page');
Route::get('/danh-muc/{slug}', [App\Http\Controllers\IndexController::class, 'category'])->name('category');
Route::get('/the-loai/{slug}', [App\Http\Controllers\IndexController::class, 'genre'])->name('genre');
Route::get('/phim/{slug}', [App\Http\Controllers\IndexController::class, 'movie'])->name('movie');
Route::get('/xem-phim/{slug}', [App\Http\Controllers\IndexController::class, 'watch'])->name('watch');
Route::get('/quoc-gia/{slug}', [App\Http\Controllers\IndexController::class, 'country'])->name('country');
Route::get('/so-tap', [App\Http\Controllers\IndexController::class, 'episode'])->name('so-tap');
Route::get('/year/{slug}', [App\Http\Controllers\IndexController::class, 'year'])->name('year');
Route::post('/update-topview-phim', [MovieController::class,'update_topview']);
Route::post('/update-season-phim', [MovieController::class,'update_season']);
Route::get('/tim-kiem', [App\Http\Controllers\IndexController::class,'search'])->name('search');
Route::get('/select-movie', [EpisodeController::class,'select_movie'])->name('select-movie');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/', App\Http\Controllers\IndexController::class);
Route::resource('/category', App\Http\Controllers\CategoryController::class);
Route::resource('/genre', App\Http\Controllers\GenreController::class);
Route::resource('/movie', App\Http\Controllers\MovieController::class);
Route::resource('/watch', App\Http\Controllers\WatchController::class);
Route::resource('/country', App\Http\Controllers\CountryController::class);
Route::resource('/episode', App\Http\Controllers\EpisodeController::class);

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    public $timestamps  = false;

    use HasFactory;

    public function movie(){
        return $this->belongsTo(Movie::class);

    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use Illuminate\Http\Request;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
         $list = Genre::all();
        return view('admincp.genre.form',compact('list'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
   
        $data = $request ->all();

         $genre = new Genre();
           
         $genre->title = $data['title'];
         $genre->slug = $data['slug'];

         $genre->description = $data['description'];
         $genre->status = $data['status'];

         $genre ->save();

         return redirect()->back();

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        // 
           $genre  = Genre::find($id);
           $list  =  Genre::all(); 

       
           return view('admincp.genre.form',compact('list','genre'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //

        $data = $request ->all();

         $genre = Genre::find($id);
           
         $genre->title = $data['title'];
         $genre->slug = $data['slug'];
         $genre->description = $data['description'];
         $genre->status = $data['status'];

         $genre ->save();

         return redirect()->back();

         
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //

        Genre::find($id)->delete();
          return redirect()->back();

    }
}

resources/views/admincp/genre/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                @if(!isset($genre))
                {!! Form::open(['route' => 'genre.store','method'=>'post']) !!}
                @else
                {!! Form::open(['route' => ['genre.update',$genre->id],'method'=>'put']) !!}
                @endif
                   
                    <div class="form-group">
                        {{ Form::label('title', 'Tiêu đề', ['class' => 'control-label']) }}
                        {{ Form::text('title',isset($genre)?$genre->title:'' , array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('slug', 'Slug', ['class' => 'control-label']) }}
                        {{ Form::text('slug',isset($genre)?$genre->slug:'' , array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('description', 'Mô tả', ['class' => 'control-label']) }}
                        {{ Form::textarea('description', isset($genre)?$genre->description:'', array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('status', 'Trạng thái', ['class' => 'control-label']) }}
                        {{ Form::select('status', [1=>'Hiển thị',0=>'Không hiển thị'], isset($genre)?$genre->status:'') }}
                    </div>

                    @if(!isset($genre))
                    {!! Form::submit('Thêm dữ liệu',['class'=>'btn btn-primary'] ) !!}

                    @else
                    {!! Form::submit('Sửa dữ liệu',['class'=>'btn btn-primary'] ) !!}

                    @endif
                {!! Form::close() !!}
                </div>
            </div>
        </div>
        <div class="col-md-12 mt-5">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Tiêu đề</th>
                    <th scope="col">SLug</th>

                    <th scope="col">Mô tả</th>
                    <th scope="col">Trạng thái</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                
                    @foreach ($list as $key => $cate) 
                    <tr>
                        <th scope="row">{{$key+1}}</th>
                    <th scope="row">{{$cate->title}}</th>
                    <th scope="row">{{$cate->slug}}</th>

                    <th scope="row">{{$cate->description}}</th>
                    <th scope="row">
                            @if ($cate->status)
                              Hiển thị
                            @else
Không hiển thị
                            @endif
                         </th>
                    <td>
                          <?php $edit?>
                          {!! Form::open(['method'=>'delete','route'=>['genre.destroy',$cate->id],'onsubmit'=>'return confirm("Xóa")']) !!}
                            {!! Form::submit('Xóa',['class'=>'btn btn-danger'] ) !!}

                    
                             {!! Form::close() !!}

                              <a href="{{route('genre.edit',$cate->id)}}" class="btn btn-warning">Sửa</a>
                    </td>
                  </tr>
                            
                  @endforeach
                 
                 
                </tbody>
              </table>
        </div>
    </div>
</div>
@endsection