routes/web.php
<?php

use App\Http\Controllers\EpisodeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MovieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('home-page');
Route::get('/danh-muc/{slug}', [App\Http\Controllers\IndexController::class, 'category'])->name('category');
Route::get('/the-loai/{slug}', [App\Http\Controllers\IndexController::class, 'genre'])->name('genre');
Route::get('/phim/{slug}', [App\Http\Controllers\IndexController::class, 'movie'])->name('movie');
Route::get('/xem-phim/{slug}', [App\Http\Controllers\IndexController::class, 'watch'])->name('watch');
Route::get('/quoc-gia/{slug}', [App\Http\Controllers\IndexController::class, 'country'])->name('country');
Route::get('/so-tap', [App\Http\Controllers\IndexController::class, 'episode'])->name('so-tap');
Route::get('/year/{slug}', [App\Http\Controllers\IndexController::class, 'year'])->name('year');
Route::post('/update-topview-phim', [MovieController::class,'update_topview']);
Route::post('/update-season-phim', [MovieController::class,'update_season']);
Route::get('/tim-kiem', [App\Http\Controllers\IndexController::class,'search'])->name('search');
Route::get('/select-movie', [EpisodeController::class,'select_movie'])->name('select-movie');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/', App\Http\Controllers\IndexController::class);
Route::resource('/category', App\Http\Controllers\CategoryController::class);
Route::resource('/genre', App\Http\Controllers\GenreController::class);
Route::resource('/movie', App\Http\Controllers\MovieController::class);
Route::resource('/watch', App\Http\Controllers\WatchController::class);
Route::resource('/country', App\Http\Controllers\CountryController::class);
Route::resource('/episode', App\Http\Controllers\EpisodeController::class);

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    public $timestamps  = false;
    

    use HasFactory;

    public function category(){
        return $this->belongsTo(Category::class,'category_id');

    }

    public function genre(){
        return $this->belongsTo(Genre::class);

    }

    public function country(){
        return $this->belongsTo(Country::class);

    }

    public function movie_genre(){
        return $this->belongsToMany(Genre::class,'movie_genre','movie_id','genre_id');
    }

    public function episode(){
        return $this->hasMany(Episode::class);
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Country;
use App\Models\Episode;
use App\Models\Genre;
use App\Models\Movie;
use App\Models\MovieGenre;
use Faker\Core\File;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //

     

    }
  
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $category = Category::pluck('title','id');
        $genre = Genre::pluck('title','id');
        $country = Country::pluck('title','id');
      
        $list = Movie::with('category','genre','country','movie_genre')->orderBy('id','desc')->get();

        //  return $list;
        $listGenre = Genre::all();
        // $path = public_path()."/json/";

        // if(!is_dir($path)){
        //     mkdir($path,0777,true);
        // }
        // File::put($path."movies.json",json_encode($list));
        // return $list;
      
        return view('admincp.movie.form',compact('list','category','genre','country','listGenre'));

    }
     
    public function update_topview(Request $request){
          $data  = $request->all();
          $movie = Movie::find($data['id_phim']);
          $movie ->top_view = $data['top_view'];
          $movie->save();
    }

    public function update_season(Request $request){
        $data  = $request->all();
        $movie = Movie::find($data['id_phim']);
        $movie ->season = $data['season'];
        return  $movie;
        $movie->save();
  }
    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //   
        $data = $request ->all();

        $movie = new Movie();
          
        $movie->title = $data['title'];
        $movie->slug = $data['slug'];
        $movie->view = rand(0,5000);

        $movie->status = $data['status'];
        $movie->phude = $data['phude'];
        $movie->trailler = $data['trailler'];

        $movie->phim_hot = $data['phim_hot'];
        $movie->year = $data['year'];
        $movie->thoi_luong_phim = $data['thoi_luong_phim'];

        $movie->description = $data['description'];
        $movie->category_id = $data['category_id'];
        // $movie->genre_id = $data['genre_id'];
        $movie->country_id = $data['country_id'];
        $movie->ngay_tao = Carbon::now('Asia/Ho_Chi_Minh');
        $movie->ngay_cap_nhat = Carbon::now('Asia/Ho_Chi_Minh');
        $get_image = $request->file('image');

        foreach($data['genre'] as $key => $gen){
            $movie ->genre_id = $gen[0];
         }

        // return $data['genre_id'];
        $path  = 'upload/movie';

         if($get_image){
            $get_name_image  = $get_image->getClientOriginalName();

            $name_image = current(explode('.',$get_name_image));
            $new_image = $name_image.rand(0,9999).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path,$new_image);
            $movie->image = $new_image;

         }


        //   return $movie;
         $movie ->save();

         $movie->movie_genre()->attach($data['genre']);


        return redirect()->back();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //

        $category = Category::pluck('title','id');
        $list = Movie::with('category','genre','country')-> orderBy('id','desc')->get();
        $genre = Genre::pluck('title','id');
        $country = Country::pluck('title','id');
        $movie = Movie::find($id);
        $listGenre = Genre::all();

// return $list;
        return view('admincp.movie.form',compact('list','category','genre','country','movie','listGenre'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
        $data = $request ->all();

        $movie =  Movie::find($id);
          
        $movie->title = $data['title'];
        $movie->slug = $data['slug'];
        $movie->trailler = $data['trailler'];

        $movie->status = $data['status'];
        $movie->phude = $data['phude'];

        $movie->phim_hot = $data['phim_hot'];
        $movie->year = $data['year'];
        $movie->thoi_luong_phim = $data['thoi_luong_phim'];
        $movie->description = $data['description'];
        $movie->category_id = $data['category_id'];
        // $movie->genre_id = $data['genre_id'];
        $movie->country_id = $data['country_id'];
        $movie->ngay_cap_nhat = Carbon::now('Asia/Ho_Chi_Minh');

        $get_image = $request->file('image');

        $path  = 'upload/movie';

         if($get_image){
            $get_name_image  = $get_image->getClientOriginalName();

            $name_image = current(explode('.',$get_name_image));
            $new_image = $name_image.rand(0,9999).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path,$new_image);
            $movie->image = $new_image;

         }

         foreach($data['genre'] as $key => $gen){
            $movie ->genre_id = $gen[0];
         }



        //  return $movie;
         $movie ->save();
         $movie ->movie_genre()->sync($data['genre']);
         
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        $movie = Movie::find($id);
        //  return $movie;
         MovieGenre::whereIn('movie_id',[$movie->id])->delete();
         Episode::whereIn('movie_id',[$movie->id])->delete();

        $movie ->delete();

        return redirect()->back();
    }
}

resources/views/admincp/movie/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                @if(!isset($movie))
                {!! Form::open(['route' => 'movie.store','method'=>'post','enctype'=>'multipart/form-data']) !!}
                @else
                {!! Form::open(['route' => ['movie.update',$movie->id],'method'=>'put','enctype'=>'multipart/form-data']) !!}
                @endif
                   
                    <div class="form-group">
                        {{ Form::label('title', 'Tiêu đề', ['class' => 'control-label']) }}
                        {{ Form::text('title',isset($movie)?$movie->title:'' , array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('slug', 'Slug', ['class' => 'control-label']) }}
                        {{ Form::text('slug',isset($movie)?$movie->slug:'' , array_merge(['class' => 'form-control'])) }}
                    </div>
                  
                  
                    <div class="form-group">
                        {{ Form::label('description', 'Mô tả', ['class' => 'control-label']) }}
                        {{ Form::textarea('description', isset($movie)?$movie->description:'', array_merge(['class' => 'form-control'])) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('trailler', 'Trailler', ['class' => 'control-label']) }}
                        {{ Form::text('trailler', isset($movie)?$movie->trailler:'', array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('status', 'Trạng thái', ['class' => 'control-label']) }}
                        {{ Form::select('status', [1=>'Hiển thị',0=>'Không hiển thị'], isset($movie)?$movie->status:'') }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('phude', 'Phụ đề', ['class' => 'control-label']) }}
                        {{ Form::select('phude', [1=>'Thuyết minh',0=>'Phụ đề'], isset($movie)?$movie->phude:'') }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('phim_hot', 'Phim hot', ['class' => 'control-label']) }}
                        {{ Form::select('phim_hot', [1=>'Hiển thị',0=>'Không hiển thị'], isset($movie)?$movie->phim_hot:'') }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('image', 'Image', ['class' => 'control-label']) }}
                        {{ Form::file('image' , array_merge(['class' => 'form-control'])) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('category_id', 'Danh mục', ['class' => 'control-label']) }}
                        {{ Form::select('category_id',$category,isset($movie)?$movie->slug:'' , array_merge(['class' => 'form-control'])) }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('category_id', 'Thể loại', ['class' => 'control-label']) }}
                        <br/>
                        @foreach ($listGenre as $key => $gen)
                        @if(isset($movie))
                        {{ Form::checkbox('genre[]',$gen->id,$movie->genre_id===$gen->id?'checked':'') }}
@else
                        {{ Form::checkbox('genre[]',$gen->id) }}
                        @endif
                        {{ Form::label('genre_id', $gen ->title, ['class' => 'control-label']) }}

                        @endforeach
                    </div>
                    <div class="form-group">
                        {{ Form::label('country', 'Country', ['class' => 'control-label']) }}
                        {{ Form::select('country_id',$country,isset($movie)?$movie->slug:'' , array_merge(['class' => 'form-control'])) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('year', 'Year', ['class' => 'control-label']) }}
                        {{ Form::text('year',isset($movie)?$movie->year:'' , array_merge(['class' => 'form-control'])) }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('thoi_luong_phim', 'Thời lượng', ['class' => 'control-label']) }}
                        {{ Form::text('thoi_luong_phim',isset($movie)?$movie->thoi_luong_phim:'' , array_merge(['class' => 'form-control'])) }}
                    </div>

                    @if(!isset($movie))
                    {!! Form::submit('Thêm dữ liệu',['class'=>'btn btn-primary'] ) !!}

                    @else
                    {!! Form::submit('Sửa dữ liệu',['class'=>'btn btn-primary'] ) !!}

                    @endif
                {!! Form::close() !!}
                </div>
            </div>
        </div>
        <div class="col-md-12 mt-5">
           <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Tiêu đề</th>
                    <th scope="col">SLug</th>

                    <th scope="col">Image</th>

                    <th scope="col">Mô tả</th>
                    <th scope="col">trailler</th>

                    <th scope="col">Trạng thái</th>
                    <th scope="col">Phụ đề</th>

                    <th scope="col">Phim hot</th>

                    <th scope="col">Thể loại</th>
                    <th scope="col">Danh mục</th>
                    <th scope="col">Quốc gia</th>
                    <th scope="col">Năm</th>
                    <th scope="col">Thời lượng</th>
                    <th scope="col">Top View</th>
                    <th scope="col">Season</th>

                    <th scope="col">Ngày tạo</th>
                    <th scope="col">Ngày cập nhật</th>
                    
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($list as $key => $cate) 
                    <tr>
                        <th scope="row">{{$key+1}}</th>
                    <th scope="row" >{{$cate->title}}</th>
                    <th scope="row" >{{$cate->slug}}</th>

                    <th scope="row"><img width="40" src="{{asset('upload/movie/'.$cate->image)}}"/></th>

                    <th scope="row">{{$cate->description}}</th>
                    <th scope="row">{{$cate->trailler}}</th>

                    <th scope="row">
                            @if ($cate->status)
                              Hiển thị
                            @else
Không hiển thị
                            @endif
                         </th>

                         <th scope="row">
                            @if ($cate->phude)
                              Thuyết minh
                            @else
Phụ đề
                            @endif
                         </th>

                         <th scope="row">
                            @if ($cate->phim_hot)
                             Hot
                            @else
Không
                            @endif
                         </th>
                        <th scope="row">
                            @foreach ($cate->movie_genre as $key =>$mov_gen)
                            <button type="button" class="btn btn-dark"> {{$mov_gen->title}}</button>
                           
                            @endforeach
                        </th>
                        <th scope="row">{{$cate->genre->title}}</th>
                        <th scope="row">{{$cate->country->title}}</th>
                        <th scope="row">{{$cate->year}}</th>
                        <th scope="row">{{$cate->thoi_luong_phim}}</th>
                       
<th scope="row">
    <form method="post">
        @csrf
        {{ Form::select('top_view', [0=>'Ngày',1=>'Tuần',2=>'Tháng'], isset($cate->top_view)?$cate->top_view:'', array_merge(['class' => 'select_top_view','id'=>$cate->id])) }}

    </form>
</th>

<th scope="row">
    <form method="post">
        @csrf
        {{ Form::selectRange('season', 0,20, isset($cate->season)?$cate->season:'0', array_merge(['class' => 'select-season','id'=>$cate->id])) }}

    </form>

</th>
                        <th scope="row">{{$cate->ngay_tao}}</th>
                        <th scope="row">{{$cate->ngay_cap_nhat}}</th>

                         <th>
                            <?php $edit?>
                            {!! Form::open(['method'=>'delete','route'=>['movie.destroy',$cate->id],'onsubmit'=>'return confirm("Xóa")']) !!}
                              {!! Form::submit('Xóa',['class'=>'btn btn-danger'] ) !!}
  
                      
                               {!! Form::close() !!}
  
                                <a href="{{route('movie.edit',$cate->id)}}" class="btn btn-warning">Sửa</a>
                         </th>
                  </tr>
                            
                  @endforeach
                 
                 
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>
@endsection